# Generated by Django 3.1.7 on 2021-04-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210318_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='generated',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=50, verbose_name='Answer'),
        ),
    ]
