# Generated by Django 3.1.7 on 2021-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210424_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='generated',
            field=models.TextField(default='', verbose_name='Generated Question'),
            preserve_default=False,
        ),
    ]
